# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  docker: circleci/docker@1.5.0

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
  publish-image:
    docker:
        - image: node:14.16.0
    steps:
      - run:
        # installs a docker client that will be used to run the docker commands
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
        # Builds a docker image to push to Docker Hub
          name: Build Docker image
          command: docker build -t ${DOCKER_USERNAME}/${DOCKER_REPO}:latest .
      - run:
        # Pushes the Docker image you created to the Docker Hub.
          name: Push to Docker Hub
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker push ${DOCKER_USERNAME}/${DOCKER_REPO}:latest
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - publish-image