# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  docker: circleci/docker@1.5.0

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
  build-and-push:
    executor: docker/docker
    steps:
    - setup_remote_docker
    - checkout
    - docker/check
    - docker/build:
        image: $DOCKER_USERNAME/$DOCKER_REPO
        tag: latest,v1
    - docker/push:
        digest-path: /tmp/digest.txt
        image: $DOCKER_USERNAME/$DOCKER_REPO
        tag: latest,v1
    - run:
        command: |
          echo "Digest is: $(</tmp/digest.txt)"
workflows:
  build-test-push:
    jobs:
      - build-and-test
      - build-and-push:
          requires:
          - build-and-test